version: '3.8'

services:
  analyzer:
    build: ./
    env_file:
      - ./config/.env
    depends_on:
      - mongodb

  mongodb:
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - ./data:/data/db
    env_file:
      - ./config/.env