name: Publish image to ghcr.io

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  publish-go-finra-short-sales-analyzer-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build the go-finra-short-sales-analyzer Docker image
        run: |
          docker build . -t ghcr.io/samgozman/go-finra-short-sales-analyzer:latest
          docker push ghcr.io/samgozman/go-finra-short-sales-analyzer:latest